### ISSUE TITLE
[Feature request] Border only for white (or other colors)

### ISSUE THREAD

**Issue by hmaesta** [saintplay/vue-swatches#15]
It would be great if there is an option to add border just for some color (mainly because of white).

Something like:
```html
<swatches v-model="input" :colors="colors" :show-border-for="borderedColors" />
```

```js
export default {
    data() {
        return {
            colors: [ '#000000', '#333333', '#999999', '#CCCCCC', '#EEEEEE', '#F4F4F4', '#FFFFFF' ],
            borderedColors: [ '#EEEEEE', '#F4F4F4', '#FFFFFF' ]
        }
    }
}
```

----

#### Temporary workaround
Right now I just need to add border for white, so I set it as my last color and apply border with SCSS.

```scss
.vue-swatches {
    .vue-swatches__container {
        .vue-swatches__wrapper {
            .vue-swatches__swatch {
                &:last-child {
                    box-shadow: inset #CCC 0 0 0 1px;
                }
            }
        }
    }
```

I also set border for the trigger, for when user select white (but appears to all colors, since it's not possible to "detect" with CSS when it's white).

```scss
.vue-swatches {
    .vue-swatches__trigger {
        box-shadow: inset #CCC 0 0 0 1px;
    }
}
```

Thank you for the great component!
