### ISSUE TITLE
border around the trigger.

### ISSUE THREAD

**Issue by NozzyEz** [saintplay/vue-swatches#71]
I know we can add `show-border` to the `v-swatches` component, and that adds a border around the swatch colors, but is there a way to also give a border to the actual trigger? i've tried to hack it with css, but that seems to do nothing

**Comment by saintplay** [comment]
Maybe that should work out of the box, or with other prop.

For now, using css should do the trick.

```css
.vue-swatches__trigger {
  border: 1px solid #ccc;
}
```
